### ISSUE TITLE
Is it possible to apply this plugin to L.TileLayer.Canvas ?

### ISSUE THREAD

**Issue by seifer08ms** [GreenInfo-Network/L.TileLayer.PixelFilter#8]
We already had a TileLayer.Canvas layer which was rendered by discrete classification . Can we use this plugin to filter some pixel values ?

**Comment by gregallensworth** [comment]
L.TileLayer.PixelFilter would not be directly applicable as-is, since it reads a PNG and then writes back a in-memory PNG.

If you're using a L.TIleLayer.Canvas then you wrote a _drawTile()_ function, yes? I imagine that would be the place to add your own logic, that pixels matching certain criteria are set to [0,0,0,0] to become transparent.

**Comment by seifer08ms** [comment]
Thanks for your tip. It is exactly the key to work. I finally made it.
